before_commands:
    - composer install --dev
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    sensiolabs_security_checker: true
filter:
    excluded_paths:
        - 'test/*'
        - 'doc/*'
        - 'vendor/*'